### ISSUE TITLE
Filters do not work in "exact match" mode

### ISSUE THREAD

**Issue by danieldietsch** [ultimate-pa/hanfor#196]
If I have a type "functional" and "nonfunctional", and select "functional", it matches both types. Using " does not help.
![image](https://user-images.githubusercontent.com/3883391/108342489-29eb6000-71db-11eb-9fc1-04d2f5c7dbe3.png)

**Comment by hauff** [comment]
I can not reproduce the described behavior.
Filtering with `Functional`, `"Functional` and `"Functional"` works as expected.

**Comment by hauff** [comment]
@danieldietsch Could you please check, if this issue exists?

**Comment by danieldietsch** [comment]
You are right, it works as intended if I use ``"``
