### ISSUE TITLE
Extension markdown-lightbox and Python >= 3.8 ... object has no attribute 'getiterator'

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/hanfor#206]
**ErrorMessage**
`Error reading page 'index.md': 'xml.etree.ElementTree.Element' object has no attribute 'getiterator'`

**Fix**
Line 31 in mdx_lightbox.py uses old-deprecated ElementTree features that where removed in Python 3.8. (see https://bugs.python.org/issue29209)

**Python < 3.8**
`images = root.getiterator("img")`

**Python >= 3.8**
`images = root.iter("img")`

The extension was updated 6 years ago, maybe we should search for some alternative?

**Comment by danieldietsch** [comment]
This is a good idea. This issue is for the documentation, correct?

**Comment by hauff** [comment]
> This issue is for the documentation, correct? 

Yes, that is correct.

**Comment by Breee** [comment]
we could try this fork: https://github.com/colinbourassa/markdown-lightbox 
As it fixes the issue: 

https://github.com/colinbourassa/markdown-lightbox/commit/f1130e920d104346b688bf589e8a0429c39aa5c1

**Comment by hauff** [comment]
> we could try this fork: https://github.com/colinbourassa/markdown-lightbox 
> As it fixes the issue: 
> 
> https://github.com/colinbourassa/markdown-lightbox/commit/f1130e920d104346b688bf589e8a0429c39aa5c1

Great, thank you. I will try this one.

**Comment by hauff** [comment]
Note (backward compatibility): `iter` is built-in in Python >= 3.5 (see https://docs.python.org/3.6/library/functions.html).
