### ISSUE TITLE
Search shows unexpected behavior OR "show all" links in variables are wrong

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/hanfor#208]
Hanfor Session: `daimler_cs`
Search: `:COL_INDEX_02:"ELS-24":OR:"ELS-33"`
Current Result: `ELS-24`, `ELS-33`, `ELS-48`
Expected Result: `ELS-24`, `ELS-33`

The search `:COL_INDEX_02:"ELS-24":OR::COL_INDEX_02:"ELS-33"` produces the expected result.
If this is the intended behavior of `COL_INDEX` and `OR`, then the `show all` links in Variables must be fixed.

---
Additional information

Occurrences of `ELS-24` and `ELS-33`
- `ELS-24`: in column `Id (2)` of `ELS-24`
- `ELS-33`: in column `Id (2)` of `ELS-33`; in column `Description (3)` of `ELS-48`

**Comment by henkele** [comment]
The result of `:COL_INDEX_02:"ELS-24":OR:"ELS-33"` is correct. The behavior of the `show all` link must be fixed.
