### ISSUE TITLE
Incorrect guard in representation of `before` scope of several patterns

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/hanfor#214]
The guard of the initial transition to location `ct0_st` should be `P`.
This seems to be the case for `before` scope of several patterns.
It is unclear if it's a bug in the representation or in the implementation.

Examples:
- AbsencePattern Before: https://ultimate-pa.github.io/hanfor/references/patterns.html#absencepattern-before
- ResponseDelayPattern Before: https://ultimate-pa.github.io/hanfor/references/patterns.html#responsedelaypattern-before

**Comment by henkele** [comment]
The representation was wrong for all countertraces whose first phase was not a true phase. This was a bug in ultimate which was fixed in https://github.com/ultimate-pa/ultimate/commit/e334897bb9b02a6ec9123dd0e3e43aaaa5bf07a0
