### ISSUE TITLE
Add commenting feature to tags

### ISSUE THREAD

**Issue by Langenfeld** [ultimate-pa/hanfor#218]
Tags on itself are not sufficent to capture most of the reports generated during formalisation.
Thus tags should be 'commentable' i.e. for each tag of a requirement one should be able to supply a comment giving more detail.

Note, that threre is already a comment feature per Tag, to describe what a tag usually means for the whole set. This is not what should be used here.

To illustrate how that could work:
![commentedtags](https://user-images.githubusercontent.com/15321150/159737051-374f3cd9-cb90-4295-b06c-278e0cae02d9.jpg)

**Comment by DaraKamalian** [comment]
I've been working on the design and I think this looks best. If you have any suggestions please tell me. I am currently working on integrating this new design with the current codebase
<img width="1440" alt="Screen Shot 2022-03-29 at 4 19 06 PM" src="https://user-images.githubusercontent.com/43106073/160633011-4d83bdf8-ffd3-4ad2-9296-b4911c328dc3.png">
.
