### ISSUE TITLE
Adding a constraint to variable discards changes made to a previous added constraint

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/hanfor#221]
Steps to reproduce:
- go to variable modal
- add a constraint and modify it
- add another constraint

Both constrains are empty.

**Comment by henkele** [comment]
Seems to be a larger problem with how the constraint modal is generated: html for the whole constraint part is generated on server side when `add_constraint` is clicked.

Requires larger refactoring: Use JS to show constraints and serve constraint data via API (like requirements modal)
