### ISSUE TITLE
Npm package precss causes build error. Is this plugin still needed?

### ISSUE THREAD

**Issue by hauff** [ultimate-pa/hanfor#222]
Npm package [precss](https://www.npmjs.com/package/precss) is disabled in dfedb4262dfb67c20dd6c7fcc3b21aaa05e5fddc, because it causes the following build error ...

```
ERROR in ./scss/custom.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].use[2]!./node_modules/sass-loader/dist/cjs.js!./scss/custom.scss)
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read properties of undefined (reading 'raws')
```

If we still need precss, this could be a workaround https://github.com/csstools/precss/issues/139#issuecomment-1000189868.

**Comment by DaraKamalian** [comment]
After removing precss from package.json and running npm build, I have tested hanfor and nothing seems to break!
So perhaps we don't need precss after all.
