### ISSUE TITLE
import example_blueprint  package error

### ISSUE THREAD

**Issue by Eevan-zq** [ultimate-pa/hanfor#226]
I don't know why there is a error follows:
![image](https://user-images.githubusercontent.com/99885690/193222485-d0e56d3d-c1bc-4d9e-a55b-621ee60ab57e.png)

I just want to try your example requirement in 
![image](https://user-images.githubusercontent.com/99885690/193222754-fe570fed-13e2-4258-90e8-349faceff165.png)

But it seems that there has errors in example_blueprint folder
![image](https://user-images.githubusercontent.com/99885690/193222970-bcfdf1b8-145d-4902-8999-bcbd55778271.png)

**Comment by Langenfeld** [comment]
What python version are you running? 
This is unfortunately already python 3.10 syntax for union type annotations (see https://docs.python.org/3/library/typing.html#typing.Union).

**Comment by Zq19491001** [comment]
My python version:
![image](https://user-images.githubusercontent.com/99885690/193224847-c9a7bca4-dc68-4a46-b8c8-9712bef9f442.png)

It means I need to update my python to 3.10 or more?

**Comment by Langenfeld** [comment]
3.10 is ok.

**Comment by Zq19491001** [comment]
Ok, thank you.
