### ISSUE TITLE
About UReqcheck-linux

### ISSUE THREAD

**Issue by Eevan-zq** [ultimate-pa/hanfor#228]
![image](https://user-images.githubusercontent.com/99885690/193994460-80f71043-94e8-4ea5-b502-3266f99cf96e.png)
Can you give more information about this two parts, as I can't "run_complete_analysis.sh" but it has "run_complete_analysis.py"

When using "run_complete_analysis.py" ,there had a problems like this:
![image](https://user-images.githubusercontent.com/99885690/193994944-3ed271cb-6c4f-4e26-a53e-2025035adbaa.png)

**Comment by Langenfeld** [comment]
This part of the documentation seems to be outdated, the ``.py`` file should be right.

Just try running the command as 
```sh
./run_complete_analysis.py -ar hanfor/example_input/example_input.req
```

**Comment by Eevan-zq** [comment]
But it still have problems:
![image](https://user-images.githubusercontent.com/99885690/194013314-7425a709-6113-47ab-b837-fbe13189b5b9.png)
by the way, I use java version:
![image](https://user-images.githubusercontent.com/99885690/194013541-754d0d8b-ead3-4293-9b4d-32cbe30510c9.png)
I don't this is ok?

**Comment by Eevan-zq** [comment]
ok it works, sorry

**Comment by hauff** [comment]
#229

**Comment by Eevan-zq** [comment]
In my Linux，My java version：
![image](https://user-images.githubusercontent.com/99885690/194022816-a9ab896f-752b-440c-9e64-9c67fd961d9f.png)
So there are no Eclipse and Maven in my Linux, and a error happen when I use above command:
![image](https://user-images.githubusercontent.com/99885690/194023294-e5eeef08-cf48-4c13-b2b6-908600baefda.png)

I don't know whether the error is because I lack Maven,Eclipse or other reasons.

**Comment by Langenfeld** [comment]
see #231
