### ISSUE TITLE
ReqAnalyser error

### ISSUE THREAD

**Issue by Eevan-zq** [ultimate-pa/hanfor#231]
Is anyone meet this error？
![image](https://user-images.githubusercontent.com/99885690/194535097-9e5bdb26-4af6-4ee0-bc60-02c477054f28.png)

**Comment by Langenfeld** [comment]
Hello Eevan,
what are you trying to do, and what are the tools you are using. How can we repdouce this problem?

**Comment by Eevan-zq** [comment]
I am using hanfor with this:
![image](https://user-images.githubusercontent.com/99885690/194538815-8e87e3f5-0636-418c-866f-037c4be00267.png)

But when I check the .log file, there is a error:
![image](https://user-images.githubusercontent.com/99885690/194539017-6d50ce6e-13b4-4662-bd10-5bded5ca4286.png)

So I check another file which is like:
![image](https://user-images.githubusercontent.com/99885690/194539159-ede8c4ee-4ae3-4591-88b6-0abcfa16222f.png)

And I follow the steps which in hanfor document ：
![image](https://user-images.githubusercontent.com/99885690/194539334-8bdb3bb5-eb85-44bf-9d43-67bdfd613cbe.png)

And my jre version is 16, I don't where is wrong

**Comment by hauff** [comment]
I think Ultimate requires Java 11. Maybe you can try that?

**Comment by Eevan-zq** [comment]
Ok, let me try it.

**Comment by hauff** [comment]
After research I am a little more convinced, that (today) Ultimate is incompatible with Java >=16.

[JEP 403: Strongly Encapsulate JDK Internals](https://openjdk.org/jeps/403)

**Comment by Eevan-zq** [comment]
okk， thanks， java11 works successfully. Thank you so much.
So finally, I think you can update some information in hanfor docuements which is outdated and also in ultimate documents which is "java version <16", because in ultimate:
![image](https://user-images.githubusercontent.com/99885690/194557657-71a4757c-eeb8-4bc9-88ee-8ee2ba0c20a1.png)
it can be more accurate.

**Comment by hauff** [comment]
You are welcome. I fixed the [Download and Installation](https://github.com/ultimate-pa/ultimate/wiki/Installation/b5a63c884d22ec9896061f393d8211142176134e#download-and-installation) section in the Ultimate wiki.
