### ISSUE TITLE
Hanfor's Specification language

### ISSUE THREAD

**Issue by Eevan-zq** [ultimate-pa/hanfor#232]
As I was formalizing two requirements, but I didn't know how to express "Not"  which is where the red line marks in the picture below.
![image](https://user-images.githubusercontent.com/99885690/195261558-0b766b93-c32c-4747-af55-d292611e4289.png)

**Comment by hauff** [comment]
You want to Point out, that EXPRessions are not explained in our documentation?

**Comment by Eevan-zq** [comment]
Maybe I can't express it clearly.
What I want to say is I'm not sure that the expression " ! IRLampsOn "is the correct form -- which is whether it can express the negative meaning of the boolean IRLampsOn.
Like this:

![image](https://user-images.githubusercontent.com/99885690/195276824-7872ff9b-10fe-4bd6-9ef1-720057e53c3c.png)

**Comment by Eevan-zq** [comment]
But I have checked the above formalization is correct, thanks a lot.

**Comment by hauff** [comment]
`!IRLampsOn` is correct.

**Comment by Eevan-zq** [comment]
By the way, are there any documents about the logical operations supported by hanfor? Such as "&&" is correct, not single"&".

**Comment by hauff** [comment]
I have added expressions to the [Specification Language](https://ultimate-pa.github.io/hanfor/introduction/index.html#requirement-formalization) section in our Documentation.
For the exact grammar see [hanfor_boogie_grammar.lark](https://github.com/ultimate-pa/hanfor/blob/ca7dd8a0f6be70d91c673bd526bbcf037e889e92/hanfor/hanfor_boogie_grammar.lark).

**Comment by Eevan-zq** [comment]
Okk, I see it, thanks a lot.
