### ISSUE TITLE
Duration Calcus to PEA

### ISSUE THREAD

**Issue by Eevan-zq** [ultimate-pa/hanfor#235]
I would like to ask if hanfor has any plug-ins or related software applications for automatically converting Duration Calculus into PEA automata.

**Comment by hauff** [comment]
Hello @Eevan-zq,

today there is no plugin to build a pea that corresponds to a given dc formula.
However, there exists code that implements this functionality in Hanfor and also in Ultimate.

What are you trying to do, maybe I can help you further?

**Comment by Eevan-zq** [comment]
Hello，
I am sorry that I didn't reply to you some time ago, because it was the Chinese new year. I would like to ask if there is any more detailed information (such as papers or books) about Duration Calcus in Hanfor. I want to understand Hanfor's expressive ability better. Thank you.

**Comment by hauff** [comment]
@Eevan-zq

Yes, there are papers about Duration Calculus in Hanfor.
I would recommend starting with the following source, as it describes the underlying idea.

[Jochen Hoenicke - Combination of Processes, Data, and Time](https://jochen-hoenicke.de/docs/csp-oz-dc.pdf)

**Comment by Eevan-zq** [comment]
Ok，thankls, I had got it.

**Comment by hauff** [comment]
You are welcome.
I think this issue can be closed.
