### ISSUE TITLE
hanfor development documentation

### ISSUE THREAD

**Issue by jokey66** [ultimate-pa/hanfor#240]
Is it possible to add some documentation to the repo that helps to start development on hanfor?
What I mean is anything that helps to understand the architecture of hanfor, to find where specific functionalities are located and - of course - some code documentation. Maybe also some hints about what development environments and methods you are using.

Also I'm missing more documentation about the usage of hanfor, e.g. the web api. The only api documentation is about search queries but when looking into the code there are also api calls do add/edit elements.

**Comment by hauff** [comment]
@jokey66 

Thank you for your request.
Unfortunately, we currently have no capacity to process this issue.
