### ISSUE TITLE
Tags cannot be deleted if not assigned to any requirement

### ISSUE THREAD

**Issue by henkele** [ultimate-pa/hanfor#241]
A tag cannot be deleted if it is not assigned to any requirement.
Currently, one first need to assign the tag to be able to delete it.

**Comment by hauff** [comment]
Its also not possible to delete tags that are assigned to a requirement.

It throws an key error in app.py https://github.com/ultimate-pa/hanfor/blob/82ad2143bddb39f302720b55b225720c63c34386/hanfor/app.py#L227C25-L227C67
