### ISSUE TITLE
Hanfor with Ultimate

### ISSUE THREAD

**Issue by xxrlzzz** [ultimate-pa/hanfor#251]
hello, I see installation, [reqanalyzer](https://ultimate-pa.github.io/hanfor/installation/installation.html#reqanalyzer) section, hanfor requires ultimate software.  

![image](https://github.com/ultimate-pa/hanfor/assets/40893153/d2dd6089-95db-4992-8079-8529b3c0b541)

I try to compile by run `makeFresh.sh`, but got a compile error from `lib.pea` module, I see there has a [nightly](https://monteverdi.informatik.uni-freiburg.de/ultimate-nightly/) build from [Jenkins](https://sopramake.informatik.uni-freiburg.de/), is there any chance can I have a copy of `UReqCheck-linux.zip` and `UReqCheck-win32.zip`, thanks a lot.

**Comment by xxrlzzz** [comment]
Is there any env or ide requirement for build ultimate?

java11 and java8 both not work for me

**Comment by hauff** [comment]
Link to Ultimate nightly builds in the documentation is outdated.
https://ultimate-pa.github.io/hanfor/installation/installation.html#reqanalyzer

**Comment by xxrlzzz** [comment]
great thank you for your reply
