### ISSUE TITLE
Boogie program

### ISSUE THREAD

**Issue by wzq179** [ultimate-pa/hanfor#252]
Hello, I am reading the paper "Scalable Analysis of Real-Time Requirement" recently, and I have some doubts about the code generation for Boogie programs mentioned in it. I was wondering if you could provide the Boogie program generated for the requirement cases discussed in the paper?

**Comment by danieldietsch** [comment]
Did you look at the artifact at https://zenodo.org/records/3341453? 
Is your question how to generate the Boogie files from the .req files?

**Comment by wzq179** [comment]
Thank you, I would like to see the generated Boogie code directly, as I'm a bit confused about some of the logic presented in the paper.

**Comment by wzq179** [comment]
Could you please clarify where I can find the generated Boogie code in 

> https://zenodo.org/records/3341453

? For example, like this: 
![image](https://github.com/ultimate-pa/hanfor/assets/83205579/0d568dbe-c651-4179-931a-4abc387c32d4)

**Comment by danieldietsch** [comment]
I guess you cannot, because it is generated in memory. I can look into it and probably generate the files for you.

**Comment by wzq179** [comment]
Thank you so much! I encountered some issues while manually writing Boogie code to simulate the description in my paper. For instance，
![image](https://github.com/ultimate-pa/hanfor/assets/83205579/dc80816f-0be7-447f-9df2-21dbc997440d)
when writing corresponding Boogie programs for the two PEA in the paper, I'm not sure what to implement next, like this:
![image](https://github.com/ultimate-pa/hanfor/assets/83205579/e5dd726f-e958-4585-8d3e-eca338596697)

And  I'll wait for your good news.

**Comment by danieldietsch** [comment]
Here are the bpl files for all but the largest (it takes quite some time for the rt-inconsistency check to find and remove all the true cases that are not part of the bpl program):
[re2019_bpl.zip](https://github.com/ultimate-pa/hanfor/files/14635475/re2019_bpl.zip)

You can see the .req files and the script I used to generate them using the latest UReqAnalyzer version.

**Comment by wzq179** [comment]
Thank you a lot, I will check them out right away.

**Comment by wzq179** [comment]
I'm sorry, could you please explain how the following two assert statements are defined
![image](https://github.com/ultimate-pa/hanfor/assets/83205579/daaa55ba-35eb-4f84-9296-53d5e41d9d48)

**Comment by danieldietsch** [comment]
They are required for the vacuity check. If this location is reachable with this state (i.e., the assertion is violated), then the requirement is not vacuous.

**Comment by wzq179** [comment]
Yes，but why is the parameter of the `check_CONSISTENCY` above directly **false**?

**Comment by danieldietsch** [comment]
Its similar: If this assert is violated, then the set of requirements is consistent in the sense that you can take at least some action.
The following verification is configured s.t. an assert is treated like `if (*) { assert expr; }`.

**Comment by wzq179** [comment]
Yes, but I'm not sure why the statement **`assert {:check_CONSISTENCY} false`** automatically generates **`expr`** as **`false`**.

**Comment by danieldietsch** [comment]
For consistency there is always only one assert and that assert is an assert false. It checks if any combination of initial states has a satisfiable invariant.

**Comment by wzq179** [comment]
I have some question about how to get Ndc(A_req3 || A_req4)：
![image](https://github.com/ultimate-pa/hanfor/assets/83205579/ba4373a1-7dfd-40eb-8f01-a3a032958c72)

If (pc_req3==2 and pc_req4==1), the computing process should be
![image](https://github.com/ultimate-pa/hanfor/assets/83205579/0b7b5b59-a9ab-4544-995a-b232067ab1fd)

And why we can simplify to be c_3<5 or c_4>=2. 

I think this will lead to stricter verification conditions, causing situations that should not trigger errors to do so.

**Comment by wzq179** [comment]
Hello Professor, may I ask if there is any way to see the generated PEA automaton scripts in the **re2019/artifact** [project?](https://zenodo.org/records/3341453) I only see how to generate TA automaton scripts from the .req files.

**Comment by Langenfeld** [comment]
Hello @wzq179, 
maybe you want to give a little more context on what you want to accomplish in order for us to be able to help you with more than just trying to answer some smaller technical detail. Also, we are always interested in applying our analysis to requirements from unfammilar domains, so I would be interested on the context of your experiments.

**Comment by wzq179** [comment]
Of course, sir. I'm interested in reproducing the paper "Scalable Analysis of Real-Time Requirements" published by your team, which can be verified using Boogie. From what I've seen, there aren't many papers on static verification using Boogie, especially those that describe the properties to be verified in a more intuitive way, such as natural language requirements, rather than using logical languages(eg. TCTL which is used by UPPAAL). Previously, Mr. Daniel Dietsch @danieldietsch  provided me with a lot of help and showed me how to generate Boogie. Now I want to compare the differences between generating PEA automata and timed automata. I have many PLC design cases on hand, and I plan to try the ability of verification through PEA, Boogie, and UPPAAL using these cases.

By the way, can you give me some advice about this question? https://github.com/ultimate-pa/hanfor/issues/252#issuecomment-2022268132
